name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.15' ]
    name: Typhon (Go ${{ matrix.go }})
    steps:
      - uses: actions/checkout@v2
        with:
          path: ./src/github.com/${{ github.repository }}
        
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
          
      - name: Install golint
        run: |
          go version
          go get -v golang.org/x/lint/golint
    
      - name: Lint
        run: |
          pwd
          echo $PATH
          echo $GOPATH
          go vet ./...
          golint .
        env:
          GOPATH: ${{ runner.workspace }}

      - name: Test
        run: |
          go test -v ./...
          go test -v -test.race ./...
        env:
          GOPATH: ${{ runner.workspace }}

